version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-jest
    versions:
    - 26.5.3
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
  - dependency-name: snowpack
    versions:
    - 3.0.13
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
